import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(shared)/Footer";
import Navbar from "./(shared)/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test Anime List",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
}: RootLayoutProps) => (
  <html lang="en">
    <body className={inter.className}>
      <Navbar />
      {children}
      <Footer />
    </body>
  </html>
);

export default RootLayout;
